// ─── Store & Category ────────────────────────────────────────────────────────

export type Store =
  | 'Coral Hipermercados'
  | 'Mi Comisariato/Hipermarket'
  | 'Ferrisariato'
  | 'Fybeca'
  | 'Pharmacys'
  | 'Kywi'
  | 'Promart';

export type StoreCategory = 'autoservicio' | 'farmacia';

// ─── Prize ───────────────────────────────────────────────────────────────────

export type PrizeType = 'cine_en_casa' | 'camiseta_ecuador';

// ─── Participant (matches DB schema) ─────────────────────────────────────────

export interface Participant {
  /** UUID primary key generated by Supabase */
  id: string;
  full_name: string;
  cedula: string;
  phone: string;
  store: Store;
  /** Public or signed URL to the invoice image in Supabase Storage */
  invoice_url: string;
  prize_type: PrizeType;
  /** ISO 8601 timestamp (TIMESTAMPTZ) */
  created_at: string;
}

// ─── Wizard Form State ────────────────────────────────────────────────────────

export interface FormData {
  full_name: string;
  cedula: string;
  phone: string;
  store: Store | '';
  /** Null until the user selects a file */
  invoice: File | null;
}

// ─── Wizard Navigation ────────────────────────────────────────────────────────

/** The wizard has six steps, each rendered one at a time */
export type WizardStep = 1 | 2 | 3 | 4 | 5 | 6;

// ─── Generic API Response ────────────────────────────────────────────────────

export type ApiResponse<T> =
  | { success: true; data: T }
  | { success: false; error: string };
